# Generated by Django 5.1.7 on 2025-03-12 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_type', models.CharField(choices=[('brain_tumor_detection', 'Brain Tumor Detection'), ('disease_prediction', 'Disease Prediction'), ('skin_cancer_detection', 'Skin Cancer Detection')], max_length=50)),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
