# Generated by Django 5.1.7 on 2025-03-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_searchhistory_result'),
        ('users', '0004_profile_created_at'),
    ]

    operations = [
    ]
