from rest_framework_simplejwt.views import TokenObtainPairView
from .serializers import MyEmailTokenObtainPairSerializer

class MyEmailTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyEmailTokenObtainPairSerializer